from pathlib import Path
import json,html
ROOT=Path(__file__).parent
BASE='https://argif-tech.github.io'
PAGES={
'index.html':('Санитарное обслуживание бизнеса в Астане','Санитарная ситуация.','Понятный порядок действий.','Дезинсекция, дератизация, дезинфекция и озонирование для бизнеса и организаций в Астане и пригороде.',['Кафе и рестораны','Магазины','Склады','Офисы','Гостиницы']),
'dlya-organizatsiy.html':('Санитарное обслуживание организаций в Астане','Один объект.','Согласованный план.','Обсуждение санитарных задач коммерческого объекта: формат, ограничения, исполнитель и документы до начала работ.',['Тип и площадь объекта','Задача и зоны','Режим работы','Документы']),
'dezinsektsiya.html':('Дезинсекция для бизнеса в Астане','Насекомые на объекте?','Начните с оценки задачи.','Дезинсекция — направление работ по насекомым. Для обсуждения важны признаки, зоны объекта и ранее принятые меры.',['Где заметили признаки','Когда появилась проблема','Какие зоны затронуты','Что уже предпринимали']),
'deratizatsiya.html':('Дератизация коммерческих объектов в Астане','Признаки грызунов.','Задача для всего объекта.','Обсуждение дератизации складов, магазинов и коммерческих помещений. Важны зоны доступа, товар, загрузка и условия объекта.',['Где обнаружены следы','Какие товары хранятся','Ворота и загрузка','Доступ и режим']),
'dezinfektsiya.html':('Дезинфекция помещений для бизнеса в Астане','Обеззараживание.','По конкретной задаче.','Метод, объём, подготовку и ограничения дезинфекции необходимо согласовать для конкретного помещения.',['Назначение помещения','Причина запроса','Площадь и поверхности','Ограничения и подготовка']),
'ozonirovanie.html':('Озонирование коммерческих помещений в Астане','Озонирование.','Сначала — применимость.','Обсуждаем, подходит ли озонирование для задачи и условий помещения. Метод не является универсальным решением всех санитарных проблем.',['Цель обработки','Источник запаха','Материалы и оборудование','Режим доступа']),
'cafe-restaurants.html':('Санитарное обслуживание кафе и ресторанов в Астане','Кухня. Зал. Хранение.','Одна санитарная задача.','Для кафе и ресторанов важно учитывать зоны приготовления и хранения, режим кухни, подготовку и условия работ.',['Кухня и зал','Хранение продуктов','Режим работы','Подготовка объекта']),
'warehouses.html':('Дератизация и дезинсекция складов в Астане','Товар. Ворота. Зоны.','Решение начинается с деталей.','Обсуждение санитарных задач склада: площадь, зонирование, товар и упаковка, погрузка, доступ и ранее принятые меры.',['Товар и упаковка','Ворота и погрузка','Площадь и зоны','Доступ к помещениям'])}
links=[('Дезинсекция','dezinsektsiya.html'),('Дератизация','deratizatsiya.html'),('Дезинфекция','dezinfektsiya.html'),('Озонирование','ozonirovanie.html')]
social=[('Instagram','https://www.instagram.com/arworks.kz/'),('Threads','https://www.threads.com/@arworks.kz'),('TikTok','https://www.tiktok.com/@arworks.kz'),('YouTube','https://www.youtube.com/channel/UCJzIrEwI9AbKlUTvXwl5AKQ')]
from urllib.parse import quote
wa='https://wa.me/77760001966?text='+quote('Здравствуйте! Нужен расчёт для коммерческого объекта. Подскажите условия обслуживания.')
analytics='''<script async src="https://www.googletagmanager.com/gtag/js?id=G-XZ648PX3Q1"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-XZ648PX3Q1');</script><script>(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};m[i].l=1*new Date();k=e.createElement(t);a=e.getElementsByTagName(t)[0];k.async=1;k.src=r;a.parentNode.insertBefore(k,a)})(window,document,'script','https://mc.yandex.ru/metrika/tag.js?id=113389386','ym');ym(113389386,'init',{clickmap:true,trackLinks:true,accurateTrackBounce:true});</script>'''
faq=[('Как обсудить обслуживание объекта?','Напишите в WhatsApp тип объекта, примерную площадь и задачу. В разговоре уточним условия и следующий шаг.'),('Какие данные нужны для первого разговора?','Тип объекта, примерная площадь и задача. Если площадь неизвестна, так и укажите. Подробности уточняются в разговоре.'),('От чего зависит стоимость?','От типа и площади объекта, характера задачи, условий доступа, выбранного метода и объёма работ. Стоимость и условия согласуются по конкретному объекту.'),('Какие условия и документы нужно согласовать?','До начала работ уточните объём, стоимость, условия подготовки и комплект документов для вашего объекта.'),('Можно ли проводить работы без остановки бизнеса?','Это зависит от метода, подготовки и ограничений конкретного объекта. Универсальную возможность работы без остановки мы не обещаем.')]
art='''<div class="control-art" aria-hidden="true"><p>AR / OBJECT SYSTEM</p><svg viewBox="0 0 480 480"><defs><linearGradient id="line"><stop stop-color="#75b699"/><stop offset="1" stop-color="#649dbb"/></linearGradient><radialGradient id="fill"><stop stop-color="#204637"/><stop offset="1" stop-color="#0d2332"/></radialGradient></defs><circle cx="240" cy="240" r="185" fill="none" stroke="#29404e"/><circle cx="240" cy="240" r="145" fill="none" stroke="#395461" stroke-dasharray="2 14"/><path d="M55 240h70m230 0h70M240 55v70m0 230v70" stroke="#4c6a78"/><path d="M240 105l104 49v112c0 55-43 93-104 121-61-28-104-66-104-121V154z" fill="url(#fill)" stroke="url(#line)" stroke-width="2"/><path d="M195 243l32 32 62-70" fill="none" stroke="url(#line)" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><circle cx="240" cy="55" r="5" fill="#7eb69d"/><circle cx="425" cy="240" r="5" fill="#729cb7"/></svg><div class="art-bottom"><span>01 / ОБЪЕКТ</span><span>02 / ЗАДАЧА</span><span>03 / УСЛОВИЯ</span></div></div>'''
nav=''.join(f'<a href="/{f}">{label}</a>' for label,f in links)
related=''.join(f'<a href="/{f}">{t}</a>' for t,f in [('Для организаций','dlya-organizatsiy.html'),('Кафе и рестораны','cafe-restaurants.html'),('Склады','warehouses.html')])
cards=''.join(f'<a class="service-card" href="/{f}"><span class="num">0{i}</span><h3>{label}</h3><span class="arrow" aria-hidden="true">↗</span></a>' for i,(label,f) in enumerate(links,1))
for file,(title,h1,h2,desc,points) in PAGES.items():
 url=BASE+('/' if file=='index.html' else '/'+file)
 org={'@context':'https://schema.org','@type':'Organization','name':'AR Works','url':BASE+'/','logo':BASE+'/ar-works-logo-v2.svg','telephone':'+77760001966','sameAs':[x[1] for x in social],'description':'Санитарное обслуживание бизнеса и организаций в Астане и пригороде.'}
 pills=''.join(f'<span>{html.escape(p)}</span>' for p in points)
 faqs=''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in faq)
 page=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="format-detection" content="telephone=no"><title>AR Works — {title}</title><meta name="description" content="{html.escape(desc)} Обсудить объект и расчёт в WhatsApp."><link rel="canonical" href="{url}"><meta property="og:title" content="AR Works — {title}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{url}"><meta property="og:image" content="{BASE}/ar-works-social-v2.png"><meta name="theme-color" content="#091722"><meta name="msvalidate.01" content="238A804F50757471FCDA6B9C3096F95F"><link rel="icon" href="/favicon-v2.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/apple-touch-icon-v2.png"><link rel="stylesheet" href="/styles.css?v=20261005-client-copy"><script type="application/ld+json">{json.dumps(org,ensure_ascii=False)}</script>{analytics}<script src="/site.js?v=20261005-client-copy" defer></script></head><body>
<a class="skip" href="#main">Перейти к содержимому</a><header><div class="wrap header"><a class="brand" href="/" aria-label="AR Works — главная"><img src="/ar-works-logo-v2.svg" alt="AR Works" width="180" height="44"></a><nav class="desktop-nav" aria-label="Основные разделы"><a href="/dlya-organizatsiy.html">Для бизнеса</a><a href="/#services">Услуги</a><a href="#process">Порядок</a><a href="#contacts">Контакты</a></nav><a class="header-phone" data-track="call-header" href="tel:+77760001966">+7 776 000 19 66</a><details class="site-menu"><summary>Меню</summary><nav aria-label="Мобильное меню">{nav}{related}<a href="#request">Обсудить объект</a></nav></details></div></header>
<main id="main"><section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="ey">Для бизнеса и организаций · Астана и пригород</p><h1>{h1}<br><span>{h2}</span></h1><p class="lead">{desc}</p><a class="button primary" href="#request">Обсудить объект и расчёт <span aria-hidden="true">↗</span></a><a class="text-link hero-link" href="#process">Как строится порядок действий</a></div>{art}</div><div class="wrap object-strip">{pills}</div></section>
<section id="services"><div class="wrap"><div class="section-heading"><div><p class="ey">Направления</p><h2>Четыре услуги.<br>Разные задачи.</h2></div><p class="muted">Объект и характер проблемы определяют формат. Метод и ограничения необходимо согласовать до работ.</p></div><div class="services">{cards}</div><div class="service-notes"><p><b>Дезинсекция</b> — задачи по насекомым.<br><b>Дератизация</b> — задачи по грызунам.</p><p><b>Дезинфекция</b> — обеззараживание.<br><b>Озонирование</b> — обсуждение применимости метода.</p></div></div></section>
<section class="objects"><div class="wrap"><p class="ey">Условия объекта</p><h2>Детали меняют решение.</h2><div class="object-grid"><a class="object-card" href="/cafe-restaurants.html"><span class="num">01 / ОБЩЕПИТ</span><h3>Кафе и рестораны</h3><p>Кухня, зал, хранение продуктов и режим работы.</p><span class="text-link">Обсудить условия →</span></a><a class="object-card" href="/warehouses.html"><span class="num">02 / ЛОГИСТИКА</span><h3>Склады и производства</h3><p>Товар, упаковка, ворота, зонирование и доступ.</p><span class="text-link">Обсудить условия →</span></a></div><p class="muted other-objects">Также обсуждаем задачи магазинов, офисов, гостиниц и других коммерческих помещений.</p></div></section>
<section id="process"><div class="wrap"><div class="section-heading"><div><p class="ey">Порядок обслуживания</p><h2>От запроса<br>к согласованным условиям.</h2></div><p class="muted">Начните с описания задачи. Условия, объём и формат обслуживания согласуются по вашему объекту.</p></div><ol class="steps"><li><span>01</span><h3>Описание объекта</h3><p>Тип, площадь, признаки проблемы и ранее принятые меры.</p></li><li><span>02</span><h3>Уточнение условий</h3><p>Зоны, доступ, режим работы, подготовка и ограничения.</p></li><li><span>03</span><h3>Согласование</h3><p>Объём, исполнитель, стоимость и документы до начала работ.</p></li><li><span>04</span><h3>Дальнейшие действия</h3><p>Условия выполнения и контроль, предусмотренные предложением.</p></li></ol></div></section>
<section id="documents" class="documents"><div class="wrap document-grid"><div><p class="ey">Прозрачные условия</p><h2>Понятные условия.<br>До начала работ.</h2><p class="muted">Обсудите объём, подготовку помещения, ограничения и документы. Условия обслуживания определяются задачей объекта.</p></div><div class="checklist"><h3>Что уточнить до работ</h3><ul><li>Формат и условия обслуживания</li><li>Документы для конкретного объекта</li><li>Подготовка помещения и ограничения</li><li>Объём, стоимость и дальнейшие действия</li></ul></div></div></section>
<section class="faq"><div class="wrap"><p class="ey">Без неопределённости</p><h2>Что важно знать.</h2>{faqs}</div></section>
<section id="request"><div class="wrap request-grid"><div><p class="ey">Первый разговор</p><h2>Расскажите<br>о вашем объекте.</h2><p class="muted">Три пункта помогут начать обсуждение. Точную площадь не знаете? Укажите приблизительную или «не знаю».</p><p class="status-copy">Для расчёта: тип объекта, примерная площадь и задача.</p><a class="text-link" data-track="whatsapp-request-direct" href="{wa}">Сразу написать в WhatsApp ↗</a></div><form id="request-form" class="ym-disable-keys"><label for="object">Тип объекта</label><select id="object" name="object" required><option value="">Выберите объект</option><option>Кафе или ресторан</option><option>Склад или производство</option><option>Магазин</option><option>Офис или бизнес-центр</option><option>Гостиница</option><option>Другой коммерческий объект</option></select><label for="area">Примерная площадь</label><input id="area" name="area" maxlength="40" placeholder="180 м² или не знаю" required><label for="problem">Задача</label><textarea id="problem" name="problem" rows="3" minlength="3" maxlength="1000" placeholder="Что заметили, где и что важно учесть?" required></textarea><p class="micro">Кнопка откроет WhatsApp. Проверьте и отправьте сообщение самостоятельно. Сайт не сохраняет данные формы.</p><button class="button primary" type="submit">Подготовить сообщение <span aria-hidden="true">↗</span></button><p id="request-status" class="micro" role="status" aria-live="polite"></p><noscript><p>Напишите в WhatsApp по ссылке рядом и укажите тип объекта, площадь и задачу.</p></noscript></form></div></section></main>
<footer id="contacts"><div class="wrap footer-grid"><div><b class="footer-brand">AR Works</b><p>Санитарное обслуживание бизнеса.<br>Астана и пригород.</p></div><div><h3>Обсудить задачу</h3><a class="contact-phone" data-track="call-footer" href="tel:+77760001966">+7 776 000 19 66</a><a data-track="whatsapp-footer" href="{wa}">WhatsApp ↗</a></div><div><h3>Направления</h3>{nav}</div></div><div class="wrap footer-bottom"><nav aria-label="Социальные сети">{''.join(f'<a href="{u}" target="_blank" rel="noopener noreferrer">{n} ↗</a>' for n,u in social)}</nav><a href="/privacy.html">Данные и аналитика</a><span>© AR Works, 2026</span></div></footer><div class="mobile-actions"><a data-track="whatsapp-sticky" href="{wa}">WhatsApp ↗</a><a data-track="call-sticky" href="tel:+77760001966">Позвонить</a></div></body></html>'''
 (ROOT/file).write_text(page)
(ROOT/'privacy.html').write_text('''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AR Works — данные и аналитика</title><link rel="stylesheet" href="/styles.css?v=20261005-client-copy"><main class="wrap legal"><a href="/">← AR Works</a><h1>Данные и аналитика</h1><p>Обновлено 5 октября 2026.</p><h2>Форма обращения</h2><p>Данные вводятся в вашем браузере и не сохраняются на сервере сайта. Кнопка формирует ссылку WhatsApp с вашим текстом. Сведения передаются WhatsApp при открытии ссылки. Проверьте текст перед отправкой. Работа WhatsApp регулируется правилами этого сервиса.</p><h2>Посещения и события</h2><p>Установлены Google Analytics 4 и Яндекс Метрика. Счётчики могут использовать cookies и технические сведения об устройстве и браузере. В наших событиях не передаются текст задачи, площадь, телефон, email или полная ссылка WhatsApp. Запись сессий Webvisor отключена.</p><h2>Контакт</h2><p>Вопросы о сайте: <a href="tel:+77760001966">+7 776 000 19 66</a>.</p></main></html>''')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE}{"/" if f=="index.html" else "/"+f}</loc><lastmod>2026-10-05</lastmod></url>' for f in PAGES)+'</urlset>')
print('Built',len(PAGES),'pages + privacy')
