const fs=require('fs'),path=require('path');const{chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.js');
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'assets');const logo=fs.readFileSync(path.join(root,'ar-works-logo-v2.svg'),'utf8');const logoUrl='data:image/svg+xml;base64,'+Buffer.from(logo).toString('base64');const ring='data:image/svg+xml;base64,'+Buffer.from(logo.replace('width="1285" height="315" viewBox="25 25 1285 315"','width="315" height="315" viewBox="25 25 315 315"')).toString('base64');
const css=`*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#edf3ef;background:#091722}.canvas{width:100vw;height:100vh;background:radial-gradient(ellipse at 100% 70%,#23594166,transparent 65%),#091722;position:relative;overflow:hidden}.white{display:inline-block;background:#f2f4ef;border-radius:14px;padding:15px 24px}.white img{width:260px;height:auto}.ey{font-size:21px;letter-spacing:3px;color:#8ac6a5}.title{font-size:80px;line-height:1.08;font-weight:700;letter-spacing:-3px}.sub{font-size:36px;color:#b7c7ce;line-height:1.5}.rule{border-top:1px solid #395764}.ring{position:absolute;width:900px;height:900px;right:-640px;top:230px;border:1px solid #3b645b;border-radius:50%}`;
async function shot(page,name,w,h,body){await page.setViewportSize({width:w,height:h});await page.setContent(`<html lang="ru"><meta charset="utf-8"><style>${css}</style><div class="canvas">${body}</div></html>`);await page.screenshot({path:path.join(out,name+'.png')});}
(async()=>{const b=await chromium.launch({executablePath:'/workspace/scratch/396b0e83131b/prior/AR_WORKS_Remotion/.render-browser/chromium',headless:true,args:['--no-sandbox','--no-zygote','--single-process','--disable-gpu']});const ctx=await b.newContext();const p=await ctx.newPage();
await shot(p,'avatar',1024,1024,`<div style="position:absolute;inset:0;background:#f2f4ef;display:flex;align-items:center;justify-content:center"><img src="${ring}" style="width:740px;height:740px"></div>`);
for(const [i,label,word]of [['01','Начать','01'],['02','Услуги','04'],['03','Объекты','AR'],['04','Порядок','→'],['05','Документы','✓'],['06','Контакты','↗']])await shot(p,'highlight-'+i,1080,1080,`<div style="position:absolute;inset:170px;border:2px solid #3d605c;border-radius:50%;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="font-size:190px;color:#8ac6a5;line-height:1">${word}</div><div style="font-size:44px;margin-top:40px">${label}</div></div>`);
const banner=`<div style="position:absolute;left:507px;top:510px;width:1546px;height:423px;padding:50px 80px;display:flex;align-items:center;justify-content:space-between"><div><div class="white"><img src="${logoUrl}"></div><p style="font-size:35px;margin:25px 0 0;color:#8ac6a5">Санитарное обслуживание бизнеса</p><p style="font-size:22px;color:#b7c7ce">Астана и пригород</p></div><div style="font-size:32px">+7 776 000 19 66</div></div><div class="ring"></div>`;
await shot(p,'youtube-banner',2560,1440,banner);
await shot(p,'facebook-cover',1640,624,`<div style="padding:100px 130px"><div class="white"><img src="${logoUrl}"></div><p class="title" style="font-size:65px;margin:40px 0 20px">Санитарное обслуживание бизнеса</p><p class="sub">Астана и пригород<br>WhatsApp · +7 776 000 19 66</p></div><div class="ring"></div>`);
await shot(p,'site-social',1200,630,`<div style="padding:62px 70px"><div class="white"><img src="${logoUrl}" style="width:210px"></div><p class="title" style="font-size:60px;margin:35px 0 20px">Санитарное обслуживание<br>бизнеса в Астане</p><p class="sub" style="font-size:27px">Астана и пригород · +7 776 000 19 66</p></div><div class="ring"></div>`);
for(const [name,head,sub]of [['story-01','Ваш объект.\nЕго условия.','Кафе · Магазины · Склады\nОфисы · Гостиницы'],['story-02','Начнём\nс трёх пунктов.','Тип объекта\nПримерная площадь\nЗадача'],['story-03','Ясность\nдо обязательств.','Исполнитель · Подготовка\nУсловия · Документы']])await shot(p,name,1080,1920,`<div style="padding:190px 80px"><div class="white"><img src="${logoUrl}"></div><p class="ey" style="margin-top:120px">AR WORKS / АСТАНА</p><div class="title" style="white-space:pre-line;margin-top:60px">${head}</div><p class="sub" style="white-space:pre-line;margin-top:50px">${sub}</p><div class="rule" style="margin-top:140px;padding-top:40px"><p style="font-size:36px;color:#8ac6a5">Обсудить задачу в WhatsApp</p><p class="sub">+7 776 000 19 66</p><p style="font-size:25px;color:#b7c7ce">Астана и пригород<br>Санитарное обслуживание бизнеса.</p></div></div><div class="ring"></div>`);
await b.close();console.log('Profile assets rendered')})().catch(e=>{console.error(e);process.exit(1)});
